In [24]:
## standard for data preprocess, reading, visualization
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

## machine learning
import statsmodels.api as sm
from sklearn.linear_model import BayesianRidge
from sklearn.svm import SVR

## evaluation
from sklearn.metrics import mean_squared_error

#read data
from google.colab import drive
drive.mount('/content/drive') #connect to gdrive

em=pd.read_csv('/content/drive/MyDrive/datasets/emails.csv') #read csv, deklarasi em
em

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 1,0,0,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 2,8,13,24,6,6,2,102,1,27,...,0,0,0,0,0,0,0,1,0,0
2,Email 3,0,0,1,0,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Email 4,0,5,22,0,5,1,51,2,10,...,0,0,0,0,0,0,0,0,0,0
4,Email 5,7,6,17,1,5,2,57,0,9,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5167,Email 5168,2,2,2,3,0,0,32,0,0,...,0,0,0,0,0,0,0,0,0,0
5168,Email 5169,35,27,11,2,6,5,151,4,3,...,0,0,0,0,0,0,0,1,0,0
5169,Email 5170,0,0,1,1,0,0,11,0,0,...,0,0,0,0,0,0,0,0,0,1
5170,Email 5171,2,7,1,0,2,1,28,2,0,...,0,0,0,0,0,0,0,1,0,1
5171,Email 5172,22,24,5,1,6,5,148,8,2,...,0,0,0,0,0,0,0,0,0,0

In [11]:
filename = '/content/drive/MyDrive/datasets/emails.csv'
em=pd.read_csv(filename)
em.head()

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 1,0,0,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 2,8,13,24,6,6,2,102,1,27,...,0,0,0,0,0,0,0,1,0,0
2,Email 3,0,0,1,0,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Email 4,0,5,22,0,5,1,51,2,10,...,0,0,0,0,0,0,0,0,0,0
4,Email 5,7,6,17,1,5,2,57,0,9,...,0,0,0,0,0,0,0,1,0,0

In [13]:
##Menampilkan ringkasan statistik
em.describe()

,the,to,ect,and,for,of,a,you,hou,in,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
count,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,...,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000
mean,6.640565,6.188128,5.143852,3.075599,3.124710,2.627030,55.517401,2.466551,2.024362,10.600155,...,0.005027,0.012568,0.010634,0.098028,0.004254,0.006574,0.004060,0.914733,0.006961,0.290023
std,11.745009,9.534576,14.101142,6.045970,4.680522,6.229845,87.574172,4.314444,6.967878,19.281892,...,0.105788,0.199682,0.116693,0.569532,0.096252,0.138908,0.072145,2.780203,0.098086,0.453817
min,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,12.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.000000,3.000000,1.000000,1.000000,2.000000,1.000000,28.000000,1.000000,0.000000,5.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,8.000000,7.000000,4.000000,3.000000,4.000000,2.000000,62.250000,3.000000,1.000000,12.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
max,210.000000,132.000000,344.000000,89.000000,47.000000,77.000000,1898.000000,70.000000,167.000000,223.000000,...,4.000000,7.000000,2.000000,12.000000,3.000000,4.000000,3.000000,114.000000,4.000000,1.000000

In [16]:
##menampilkan informasi data framenya
em.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5172 entries, 0 to 5171
Columns: 3002 entries, Email No. to Prediction
dtypes: int64(3001), object(1)
memory usage: 118.5+ MB

In [18]:
##Menampilkan korelasi antar tabel data, agak berat ya runningnya. harap bersabar
em.corr()

<ipython-input-18-c20e61b85b99>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  em.corr()

,the,to,ect,and,for,of,a,you,hou,in,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
the,1.000000,0.852715,0.337249,0.841200,0.784112,0.796397,0.784451,0.471392,0.303621,0.845670,...,0.008926,0.075479,0.225586,0.223426,0.101768,0.129466,0.127019,0.341878,0.051021,-0.004421
to,0.852715,1.000000,0.375480,0.825474,0.781971,0.752722,0.896466,0.508513,0.347993,0.881759,...,0.013250,0.101247,0.232847,0.255793,0.093322,0.091639,0.120059,0.406666,0.071388,0.055277
ect,0.337249,0.375480,1.000000,0.272863,0.369777,0.178028,0.400009,0.155783,0.974152,0.298387,...,0.134339,0.031431,0.046080,0.061550,0.004393,-0.007690,0.004368,0.141460,0.002492,-0.120782
and,0.841200,0.825474,0.272863,1.000000,0.751287,0.809665,0.815196,0.476764,0.235953,0.874276,...,0.005151,0.104454,0.272963,0.253440,0.151980,0.084147,0.124766,0.400225,0.042484,0.114364
for,0.784112,0.781971,0.369777,0.751287,1.000000,0.681457,0.744098,0.495852,0.329051,0.762659,...,0.022168,0.041775,0.236213,0.213631,0.134469,0.067151,0.121057,0.301074,0.038126,-0.003101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
military,0.129466,0.091639,-0.007690,0.084147,0.067151,0.073004,0.111685,0.006498,0.005429,0.120620,...,-0.002249,-0.002979,0.043408,0.104297,0.041300,1.000000,0.055227,0.049524,0.010835,0.064850
allowing,0.127019,0.120059,0.004368,0.124766,0.121057,0.108786,0.105358,0.082757,-0.000966,0.138099,...,-0.002675,-0.003543,-0.005130,0.018550,0.276001,0.055227,1.000000,0.096212,-0.003995,0.011279
ff,0.341878,0.406666,0.141460,0.400225,0.301074,0.444252,0.464473,0.195058,0.114210,0.448303,...,0.005403,0.073690,0.130356,0.164296,0.114092,0.049524,0.096212,1.000000,0.049690,0.135479
dry,0.051021,0.071388,0.002492,0.042484,0.038126,0.026403,0.093822,0.028883,0.000601,0.077751,...,-0.003373,0.035028,-0.006468,0.018939,-0.003137,0.010835,-0.003995,0.049690,1.000000,-0.006260
Prediction,-0.004421,0.055277,-0.120782,0.114364,-0.003101,0.197234,0.107776,0.130293,-0.128340,0.154055,...,-0.030375,-0.031694,0.098775,0.064315,0.038161,0.064850,0.011279,0.135479,-0.006260,1.000000

In [19]:
X = em.drop(['Email No.', 'Prediction'], axis = 'columns')
y = em['Prediction']

In [22]:
## Scikit-learn
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=47, stratify=y)

In [25]:

# Buat objek model Linear Regression
model = LinearRegression()

# Latih model dengan data training
model.fit(X_train, y_train)

LinearRegression()

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
logistic_model = LogisticRegression(max_iter=1000)

In [29]:
logistic_model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [30]:
pred_1_LM = logistic_model.predict(X_test)

In [32]:
from sklearn.metrics import classification_report

In [33]:
print("\0.25[1m" + "LOGISTIC REGRESSION RESULT : " + "\030[0m")
print(classification_report(pred_1_LM, y_test))

 .25[1mLOGISTIC REGRESSION RESULT : [0m
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       918
           1       0.95      0.95      0.95       375

    accuracy                           0.97      1293
   macro avg       0.97      0.97      0.97      1293
weighted avg       0.97      0.97      0.97      1293

In [34]:
from sklearn.tree import DecisionTreeClassifier

In [35]:
dtree_model = DecisionTreeClassifier()
dtree_model.fit(X_train, y_train)
pred_3_DC = dtree_model.predict(X_test)
print("\025[1m" + "DECISION TREE RESULT : " + "\025[0m")
print(classification_report(pred_3_DC, y_test))

[1mDECISION TREE RESULT : [0m
              precision    recall  f1-score   support

           0       0.95      0.95      0.95       916
           1       0.89      0.88      0.89       377

    accuracy                           0.93      1293
   macro avg       0.92      0.92      0.92      1293
weighted avg       0.93      0.93      0.93      1293

In [36]:
from sklearn.svm import SVC

In [39]:
svm_model = SVC()
svm_model.fit(X_train, y_train)
pred_4_SVC = svm_model.predict(X_test)
print("\025[1m" + "SVM RESULT : " + "\025[0m")
print(classification_report(pred_4_SVC, y_test))

[1mSVM RESULT : [0m
              precision    recall  f1-score   support

           0       0.98      0.81      0.89      1115
           1       0.43      0.90      0.58       178

    accuracy                           0.82      1293
   macro avg       0.71      0.86      0.73      1293
weighted avg       0.91      0.82      0.84      1293

In [40]:
from sklearn.naive_bayes import GaussianNB

In [41]:
NB_model = GaussianNB()
NB_model.fit(X_train, y_train)
pred_5_NB = NB_model.predict(X_test)
print("\030[1m" + "NAIVE BAYES RESULT : "  + "\030[0m")
print(classification_report(pred_5_NB, y_test))

[1mNAIVE BAYES RESULT : [0m
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       898
           1       0.94      0.90      0.92       395

    accuracy                           0.95      1293
   macro avg       0.95      0.94      0.94      1293
weighted avg       0.95      0.95      0.95      1293

In [42]:
from sklearn.neural_network import MLPClassifier

In [43]:
MPL_model = MLPClassifier()
MPL_model.fit(X_train, y_train)
pred_6_MPL = MPL_model.predict(X_test)
print("\025[1m" + "NEURAL NETWORK RESULT : " + "\025[0m")
print(classification_report(pred_6_MPL, y_test))

[1mNEURAL NETWORK RESULT : [0m
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       917
           1       0.97      0.97      0.97       376

    accuracy                           0.98      1293
   macro avg       0.98      0.98      0.98      1293
weighted avg       0.98      0.98      0.98      1293